# This is a basic workflow to help you get started with Actions

name: test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - name: terraform version
        run: |
          terraform version
      - name: terraform init
        run: |
          terraform init
      - name: terraform test
        run: |
          terraform test 